services:

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: emotrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "7070:7070"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=emotrack
      - DB_USER=postgres
      - DB_PASSWORD=password123

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

volumes:
  postgres_data: